import { Box, Heading } from "@chakra-ui/react";
import Image from "next/image";
import styles from "./style.module.css";
const PhotoGallery = () => {
  return (
    <Box>
      <Heading size={"lg"} mb={"30px"}>
        Tadbirdan Lavhalar
      </Heading>
      {/*    gallery */}
      <Box className={styles.galleryScroller}>
        <Box className={styles.galleryScroller__inner_reversed}>
          <Image
            className={styles.galleryImg}
            src={"/party/party1.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party2.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party3.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party4.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party5.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party6.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party7.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party8.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party9.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party10.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
        </Box>

        <Box className={styles.galleryScroller__inner}>
          <Image
            className={styles.galleryImg}
            src={"/party/party1.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party2.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party3.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party4.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party5.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party6.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party7.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party8.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party9.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
          <Image
            className={styles.galleryImg}
            src={"/party/party10.avif"}
            alt={"party1"}
            width={"200"}
            height={100}
          />
        </Box>
      </Box>
    </Box>
  );
};

export default PhotoGallery;
