import Footer from '@/components/Footer'
import Header from '@/components/Header'
import LanguageProvider from '@/context/LanguageProvider'
import OurServiceModalProvider from '@/context/OurServiceModalProvider'
import { ChakraProvider } from '@/providers/ChakraProvider'
import { Container } from '@chakra-ui/react'
import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='uz'>
			<body suppressHydrationWarning={true}>
				<ChakraProvider>
					<LanguageProvider>
						<OurServiceModalProvider>
							<Header />
							<main className={'main'}>
								<Container maxW={'1400px'}>{children}</Container>
							</main>
							<Footer />
						</OurServiceModalProvider>
					</LanguageProvider>
				</ChakraProvider>
			</body>
		</html>
	)
}
