import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header'
import CalculateTotalProvider from '@/context/CalculateTotalProvider'
import OurServiceModalProvider from '@/context/OurServiceModalProvider'
import { ChakraProvider } from '@/providers/ChakraProvider'
import { Container } from '@chakra-ui/react'
import './globals.css'
// import {Sahitya} from 'next/font/google'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children, params: { locale } }) {
	return (
		<html lang={locale}>
			<body suppressHydrationWarning={true}>
				<ChakraProvider>
					<OurServiceModalProvider>
						<CalculateTotalProvider>
							<Header />
							<main className={'main'}>
								<Container maxW={'1400px'}>{children}</Container>
							</main>
							<Footer />
						</CalculateTotalProvider>
					</OurServiceModalProvider>
				</ChakraProvider>
			</body>
		</html>
	)
}
